name: preflight-project

services:
  mysql:
    image: mysql:8.0
    container_name: pf-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pf-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  backend:
    container_name: pf-backend
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - pf-net
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      MYSQL_APP_USER: ${MYSQL_APP_USER}
      MYSQL_APP_PASSWORD: ${MYSQL_APP_PASSWORD}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      DEBUG: pf-backend
    restart: always
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    container_name: pf-frontend
    image: ${FRONTEND_IMAGE_NAME}
    build:
      context: ./preflight-frontend
      args:
        NEXT_PUBLIC_ENDPOINT: ${NEXT_PUBLIC_ENDPOINT}
    ports:
      - "${FRONTEND_PORT}:4000"
    networks:
      - pf-net
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_ENDPOINT: ${NEXT_PUBLIC_ENDPOINT}

volumes:
  mysql-data:


networks:
  pf-net:
    driver: bridge